In [1]:
import os
import pandas as pd
import json
from dotenv import load_dotenv

In [2]:
#Opening json files with api call responses

f1 = open('data/api_responses/weather1.json')
f2 = open('data/api_responses/weather2.json')
f3 = open('data/api_responses/weather3.json')
f4 = open('data/api_responses/weather4.json')

In [3]:
#Loading json files and saving as responses

responses1 = json.load(f1)
responses2 = json.load(f2)
responses3 = json.load(f3)
responses4 = json.load(f4)

In [4]:
# Calculate the numbers list for loops below based on how many responses in each json file
numbers1 = list(range(0, 4024))
numbers2 = list(range(0,23777))
numbers3 = list(range(0, 21476))
numbers4 = list(range(0, 1400))

display(len(responses1))
display(len(responses2))
display(len(responses3))
display(len(responses4))

errors = []
responses_clean = []

4024

23777

21476

1400

In [5]:
#Run for loops to remove errored out API calls

for number in numbers1:
    x = number
    x1 = len(responses1[x])
    if x1 == 4:
        responses_clean.append(responses1[x])
for number in numbers2:
    x = number
    x1 = len(responses2[x])
    if x1 == 4:
        responses_clean.append(responses2[x])
for number in numbers3:
    x = number
    x1 = len(responses3[x])
    if x1 == 4:
        responses_clean.append(responses3[x])
for number in numbers4:
    x = number
    x1 = len(responses4[x])
    if x1 == 4:
        responses_clean.append(responses4[x])

In [6]:
#Begin cleaning data by normalizing top level and creating index to work with
cleaned_data = pd.json_normalize(responses_clean)
cleaned_data

,request.type,request.query,request.language,request.unit,location.name,location.country,location.region,location.lat,location.lon,location.timezone_id,...,historical.2021-02-28.astro.moonset,historical.2021-02-28.astro.moon_phase,historical.2021-02-28.astro.moon_illumination,historical.2021-02-28.mintemp,historical.2021-02-28.maxtemp,historical.2021-02-28.avgtemp,historical.2021-02-28.totalsnow,historical.2021-02-28.sunhour,historical.2021-02-28.uv_index,historical.2021-02-28.hourly
0,Zipcode,34231,en,m,Sarasota,USA,Florida,27.272,-82.517,America/New_York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Zipcode,34201,en,m,Bradenton,USA,Florida,27.403,-82.477,America/New_York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zipcode,33710,en,m,Saint Petersburg,USA,Florida,27.789,-82.729,America/Kentucky/Monticello,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Zipcode,34994,en,m,Stuart,USA,Florida,27.198,-80.253,America/New_York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Zipcode,32309,en,m,Tallahassee,USA,Florida,30.597,-84.042,America/New_York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47653,Zipcode,32812,en,m,Orlando,USA,Florida,28.490,-81.320,America/New_York,...,07:57 AM,Full Moon,90.0,20.0,29.0,25.0,0.0,11.6,5.0,"[{'time': 0, 'temperature': 29, 'wind_speed': ..."
47654,Zipcode,32821,en,m,Orlando,USA,Florida,28.379,-81.468,America/New_York,...,07:58 AM,Full Moon,90.0,20.0,29.0,25.0,0.0,11.6,7.0,"[{'time': 0, 'temperature': 29, 'wind_speed': ..."
47655,Zipcode,33418,en,m,Palm Beach Gardens,USA,Florida,26.860,-80.140,America/New_York,...,07:52 AM,Full Moon,90.0,24.0,26.0,25.0,0.0,8.7,6.0,"[{'time': 0, 'temperature': 26, 'wind_speed': ..."
47656,Zipcode,32504,en,m,Pensacola,USA,Florida,30.490,-87.180,America/Chicago,...,07:23 AM,Full Moon,90.0,20.0,24.0,22.0,0.0,4.2,5.0,"[{'time': 0, 'temperature': 24, 'wind_speed': ..."
47657,Zipcode,33322,en,m,Fort Lauderdale,USA,Florida,26.150,-80.270,America/New_York,...,07:52 AM,Full Moon,90.0,24.0,28.0,26.0,0.0,8.7,6.0,"[{'time': 0, 'temperature': 28, 'wind_speed': ..."

In [7]:
#Cleaning hourly data which is average for the day based on input interval in the api call request made

daily_data = []

for response in responses_clean:
    normalize = pd.json_normalize(response['historical'][list(response['historical'].keys())[0]]['hourly'])
    daily_data.append(normalize)
    
daily_data = pd.concat(daily_data)
daily_data['index'] = cleaned_data.index
daily_data = daily_data.set_index('index')

In [8]:
daily_data

,time,temperature,wind_speed,wind_degree,wind_dir,weather_code,weather_icons,weather_descriptions,precip,humidity,...,chanceofremdry,chanceofwindy,chanceofovercast,chanceofsunshine,chanceoffrost,chanceofhightemp,chanceoffog,chanceofsnow,chanceofthunder,uv_index
index,,,,,,,,,,,,,,,,,,,,,
0,0,23,25,148,SSE,116,[https://assets.weatherstack.com/images/wsymbo...,[Partly cloudy],0.0,82,...,0,0,0,0,0,0,0,0,0,6
1,0,24,24,150,SSE,116,[https://assets.weatherstack.com/images/wsymbo...,[Partly cloudy],0.0,79,...,0,0,0,0,0,0,0,0,0,6
2,0,21,26,155,SSE,116,[https://assets.weatherstack.com/images/wsymbo...,[Partly cloudy],0.0,83,...,0,0,0,0,0,0,0,0,0,6
3,0,26,20,149,SSE,116,[https://assets.weatherstack.com/images/wsymbo...,[Partly cloudy],0.0,75,...,0,0,0,0,0,0,0,0,0,6
4,0,23,17,165,SSE,353,[https://assets.weatherstack.com/images/wsymbo...,[Light rain shower],2.1,90,...,0,0,0,0,0,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47653,0,29,14,150,SSE,143,[https://assets.weatherstack.com/images/wsymbo...,[Mist],0.0,74,...,0,0,0,0,0,0,0,0,0,5
47654,0,29,16,152,SSE,116,[https://assets.weatherstack.com/images/wsymbo...,[Partly cloudy],0.0,71,...,0,0,0,0,0,0,0,0,0,7
47655,0,26,23,135,SE,176,[https://assets.weatherstack.com/images/wsymbo...,[Patchy rain possible],0.2,74,...,0,0,0,0,0,0,0,0,0,6
47656,0,24,14,168,SSE,248,[https://assets.weatherstack.com/images/wsymbo...,[Fog],2.2,88,...,0,0,0,0,0,0,0,0,0,5
47657,0,28,24,124,ESE,119,[https://assets.weatherstack.com/images/wsymbo...,[Cloudy],0.0,66,...,0,0,0,0,0,0,0,0,0,6

In [9]:
# Cleaning second level of data which has historical information needed but nests it into seperate columns.  This removes the nesting that would happen if just json_normalizing
historical_data = []

for response in responses_clean:
    normalize = pd.json_normalize(response['historical'][list(response['historical'].keys())[0]])
    historical_data.append(normalize)

In [ ]:
# Connecting data together and providing index
historical_data  = pd.concat(historical_data)
historical_data['index'] = cleaned_data.index
historical_data = historical_data.set_index('index')

In [ ]:
historical_data

In [ ]:
#selecting columns wanted from cleaned_data dataframe
cleaned_data_col = [
'request.type',
'request.query',
'request.language',
'request.unit',
'location.name',
'location.country',
'location.region',
'location.lat',
'location.lon',
'location.timezone_id',
'location.utc_offset',
]

In [ ]:
#Creating df_weather_data
df_weather_data = []

In [ ]:
#Connecting all 3 tables together 

df_weather_data = pd.concat([cleaned_data[cleaned_data_col], daily_data, historical_data], axis=1)

In [ ]:
# Last dropping of columns to get data down to desirable data
df_weather_data = df_weather_data.drop(columns=[
 'time',
 'wind_speed',
 'wind_degree',
 'wind_dir',
 'weather_code', 
 'weather_icons',
 'weather_descriptions',
 'chanceofrain',
 'chanceofremdry',
 'chanceofwindy',
 'chanceofovercast',
 'chanceofsunshine',
 'chanceoffrost',
 'chanceofhightemp',
 'chanceoffog',
 'chanceofsnow',
 'chanceofthunder',
 'uv_index',
 'date_epoch',
 'uv_index',
 'astro.sunrise',
 'astro.sunset',
 'astro.moonrise',
 'astro.moonset',
 'astro.moon_phase',
 'astro.moon_illumination',
 'hourly'])

In [ ]:
display(df_weather_data.head())
display(df_weather_data.tail())

In [ ]:
#exporting cleaned data to csv
df_weather_data.to_csv('data/cleaned_data/df_weather_data.csv')